spring.application.name=atelier-api
spring.profiles.default=local
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.flyway.enabled=true
server.port=${PORT:8081}
server.error.include-message=never
server.error.include-stacktrace=never
app.cors-origins=${CORS_ORIGINS:http://localhost:4200}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
jwt.secret=${JWT_SECRET}
